openstack_security_groups: []
openstack_server_state: present
openstack_cloud: "a085-project"

openstack_servers:

  - instance_name: app1
    AnsibleGroup: backend_servers
    deployment: prod
    security_group_name: "a085-HostSG"
    image: "{{ _server_image | default('rhel-8.3') }}"
    openstack_cloud: "a085-project"
    flavor: GLOBAL-CPU_4_Memory_32768_Disk_60_flavor
    key_name: "a085-keypair"
    network: "a085-prod-network"
  - instance_name: app2
    AnsibleGroup: backend_servers
    deployment: prod
    security_group_name: "a085-HostSG"
    image: "{{ _server_image | default('rhel-8.3') }}"
    openstack_cloud: "a085-project"
    flavor: GLOBAL-CPU_4_Memory_32768_Disk_60_flavor
    key_name: "a085-keypair"
    network: "a085-prod-network"
  - instance_name: appdb1
    AnsibleGroup: database_servers
    deployment: prod
    security_group_name: "a085-HostSG"
    image: "{{ _server_image | default('rhel-8.3') }}"
    openstack_cloud: "a085-project"
    flavor: GLOBAL-CPU_4_Memory_32768_Disk_60_flavor
    key_name: "a085-keypair"
    network: "a085-prod-network"
  - instance_name: appfrontend1
    AnsibleGroup: load_balancers
    deployment: prod
    security_group_name: "a085-HostSG"
    image: "{{ _server_image | default('rhel-8.3') }}"
    openstack_cloud: "a085-project"
    flavor: GLOBAL-CPU_4_Memory_32768_Disk_60_flavor
    key_name: "a085-keypair"
    network: "a085-prod-network"