---
# change the repository to a valid one, to install PGSQL 10 on top of RHEL 8
postgres_rhel7_repo: "https://download.postgresql.org/pub/repos/yum/reporpms/EL-6-x86_64/pgdg-redhat-repo-42.0-11.noarch.rpm"
postgres_packages:
  - postgresql
  - postgresql-server 
  - postgresql-contrib 
  - postgresql-libs
postgres_library: python3-psycopg2
postgres_10_data_dir: /var/lib/pgsql/data
postgres_10_bin_path: /usr/pgsql-10/bin
postgres_service: postgresql.service
postgres_port: 5432
postgres_user: postgres
postgres_users:
  - name: flask
    password: redhat
    database: flask_db
    state: present
    priv: ALL
postgres_databases:
  - name: flask_db
    owner: flask
  - name: books_store
    owner: flask

