
---
- name: Deploy, configure, and populate Postgres 10
  hosts: database_servers
  roles:
    - role: firewall
      vars:
        firewall_services:
          - postgresql
        firewall_tcp_ports:
          - 5432
    - role: postgresql-server

  gather_facts: false
  tags:
    - database_servers